export const OKAN = {
  name: "OKAN COFFEE HOUSE",
  shortName: "OKAN",
  category: "Specialty Coffee House",
  country: "Kuwait",
  countryCode: "KW",
  governorate: "Hawalli Governorate",
  city: "Salmiya",
  address: "82QX+HXM, Salmiya, Hawalli Governorate, Kuwait",
  plusCode: "82QX+HXM",
  latitude: 29.3389192,
  longitude: 48.0498085,
  googlePlaceId: "ChIJRaZSBgCdzz8RPW42m0c0gM8",
  timezone: "Asia/Kuwait",
  currency: "KWD",
  phone: "+965 55089218",
  email: "okancoffeebar@gmail.com",
  instagramHandle: "@okancoffee",
  instagramUrl: "https://www.instagram.com/okancoffee",
  tiktokHandle: "@okancoffee_",
  tiktokUrl: "https://www.tiktok.com/@okancoffee_",
  whatsappUrl: "https://wa.me/96555089218",
  journalUrl:
    "https://hsobzzqfsxdnnwnlcxrl.supabase.co/storage/v1/object/public/link-documents/25b34cf5-e3b0-4efe-b8e5-4a3865fd9c4d/1785271447310_5cuy5j_okan_-_journal.pdf",
  logoColorSrc: "/images/okan-logo-color.svg",
  logoReverseSrc: "/images/okan-logo-reverse.svg",
  instagramQrSrc: "/images/okan-instagram-qr.svg",
  mapsUrl:
    "https://www.google.com/maps/place/?q=place_id:ChIJRaZSBgCdzz8RPW42m0c0gM8",
  mapsEmbedUrl:
    "https://www.google.com/maps?q=29.3389192,48.0498085&z=16&output=embed",
  hours: {
    sunday: "7:00 AM – 12:00 AM",
    monday: "7:00 AM – 12:00 AM",
    tuesday: "7:00 AM – 12:00 AM",
    wednesday: "7:00 AM – 12:00 AM",
    thursday: "7:00 AM – 12:00 AM",
    friday: "7:00 AM – 12:00 AM",
    saturday: "7:00 AM – 12:00 AM",
  },
  openingHoursIso: {
    days: ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"] as const,
    opens: "07:00",
    closes: "24:00",
  },
} as const;
